all:
	mkdir -p ../bin
	@echo "Notre projet est fait en Python ! Ce MakeFile ne fait que copier coller les programmes dans le bon fichier"
	cp serveur1-abeille.py ../bin/serveur1-abeille
	cp serveur2-abeille.py ../bin/serveur2-abeille
	cp serveur3-abeille.py ../bin/serveur3-abeille
	chmod +x ../bin/serveur1-abeille
	chmod +x ../bin/serveur2-abeille
	chmod +x ../bin/serveur3-abeille
	